#!/usr/bin/env python3
# 2015, m.zumstrull@syseleven.de

import html5lib
import os
import requests
import subprocess
import sys

NS = {"html": "http://www.w3.org/1999/xhtml"}

QUOBYTE_CLIENT = "/usr/bin/mount.quobyte"

def main():
    if not os.path.isfile(QUOBYTE_CLIENT):
        print("WARNING - Quobyte client is not installed")
        sys.exit(1)

    # HACK For some reason, mount.quobyte considers --version an error.
    try:
        output = subprocess.check_output([QUOBYTE_CLIENT, "--version"])
    except subprocess.CalledProcessError as e:
        output = e.output
    installed_version = output.decode().strip().split(None, 1)[1]
    print("OK - Quobyte Client %s is installed" % (installed_version,))

    warnings = 0

    for port in range(55000, 55020):
        try:
            statuspage = requests.get("http://127.0.0.1:%d/" % (port,))
            tree = html5lib.parse(statuspage.content)
            rows = tree.iterfind(".//html:table[@class='mainTable']/html:tbody/html:tr", NS)
            clientdata = {}
            for tr in rows:
                key = (tr[0].text or "").strip()
                val = (tr[1].text or "").strip()
                clientdata[key] = val
            running_version = clientdata["Quobyte: Release"]
            if running_version != installed_version:
                print("WARNING - Client on port %d is running different release %s" % (port, running_version))
                warnings += 1
            else:
                print("OK - Client on port %d is running release %s" % (port, clientdata["Quobyte: Release"]))
        except requests.exceptions.ConnectionError:
            # We don't care, we only want to check the client version
            # if there is a client there.
            pass

    if warnings:
        sys.exit(1)

if __name__ == "__main__":
    main()
